name: Crowdin Sync

on:
  push:
    branches: [ "main" ]

jobs:
  crowdin-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin Sync
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          source: strings/en-GB.json
          translation: strings/%locale%.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
